/*
PDFGen API

The PDFGen API for HTML to PDF generation.

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the GithubComTcrisseappPdfgenInternalHandlersRestapiUtilsCreateTemplateRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GithubComTcrisseappPdfgenInternalHandlersRestapiUtilsCreateTemplateRequest{}

// GithubComTcrisseappPdfgenInternalHandlersRestapiUtilsCreateTemplateRequest struct for GithubComTcrisseappPdfgenInternalHandlersRestapiUtilsCreateTemplateRequest
type GithubComTcrisseappPdfgenInternalHandlersRestapiUtilsCreateTemplateRequest struct {
	// Alias of template
	Alias string `json:"alias"`
	// HTML used for generation
	Html string `json:"html"`
	// Name of template
	Name string `json:"name"`
}

// NewGithubComTcrisseappPdfgenInternalHandlersRestapiUtilsCreateTemplateRequest instantiates a new GithubComTcrisseappPdfgenInternalHandlersRestapiUtilsCreateTemplateRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGithubComTcrisseappPdfgenInternalHandlersRestapiUtilsCreateTemplateRequest(alias string, html string, name string) *GithubComTcrisseappPdfgenInternalHandlersRestapiUtilsCreateTemplateRequest {
	this := GithubComTcrisseappPdfgenInternalHandlersRestapiUtilsCreateTemplateRequest{}
	this.Alias = alias
	this.Html = html
	this.Name = name
	return &this
}

// NewGithubComTcrisseappPdfgenInternalHandlersRestapiUtilsCreateTemplateRequestWithDefaults instantiates a new GithubComTcrisseappPdfgenInternalHandlersRestapiUtilsCreateTemplateRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGithubComTcrisseappPdfgenInternalHandlersRestapiUtilsCreateTemplateRequestWithDefaults() *GithubComTcrisseappPdfgenInternalHandlersRestapiUtilsCreateTemplateRequest {
	this := GithubComTcrisseappPdfgenInternalHandlersRestapiUtilsCreateTemplateRequest{}
	return &this
}

// GetAlias returns the Alias field value
func (o *GithubComTcrisseappPdfgenInternalHandlersRestapiUtilsCreateTemplateRequest) GetAlias() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Alias
}

// GetAliasOk returns a tuple with the Alias field value
// and a boolean to check if the value has been set.
func (o *GithubComTcrisseappPdfgenInternalHandlersRestapiUtilsCreateTemplateRequest) GetAliasOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Alias, true
}

// SetAlias sets field value
func (o *GithubComTcrisseappPdfgenInternalHandlersRestapiUtilsCreateTemplateRequest) SetAlias(v string) {
	o.Alias = v
}

// GetHtml returns the Html field value
func (o *GithubComTcrisseappPdfgenInternalHandlersRestapiUtilsCreateTemplateRequest) GetHtml() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Html
}

// GetHtmlOk returns a tuple with the Html field value
// and a boolean to check if the value has been set.
func (o *GithubComTcrisseappPdfgenInternalHandlersRestapiUtilsCreateTemplateRequest) GetHtmlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Html, true
}

// SetHtml sets field value
func (o *GithubComTcrisseappPdfgenInternalHandlersRestapiUtilsCreateTemplateRequest) SetHtml(v string) {
	o.Html = v
}

// GetName returns the Name field value
func (o *GithubComTcrisseappPdfgenInternalHandlersRestapiUtilsCreateTemplateRequest) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *GithubComTcrisseappPdfgenInternalHandlersRestapiUtilsCreateTemplateRequest) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *GithubComTcrisseappPdfgenInternalHandlersRestapiUtilsCreateTemplateRequest) SetName(v string) {
	o.Name = v
}

func (o GithubComTcrisseappPdfgenInternalHandlersRestapiUtilsCreateTemplateRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GithubComTcrisseappPdfgenInternalHandlersRestapiUtilsCreateTemplateRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["alias"] = o.Alias
	toSerialize["html"] = o.Html
	toSerialize["name"] = o.Name
	return toSerialize, nil
}

type NullableGithubComTcrisseappPdfgenInternalHandlersRestapiUtilsCreateTemplateRequest struct {
	value *GithubComTcrisseappPdfgenInternalHandlersRestapiUtilsCreateTemplateRequest
	isSet bool
}

func (v NullableGithubComTcrisseappPdfgenInternalHandlersRestapiUtilsCreateTemplateRequest) Get() *GithubComTcrisseappPdfgenInternalHandlersRestapiUtilsCreateTemplateRequest {
	return v.value
}

func (v *NullableGithubComTcrisseappPdfgenInternalHandlersRestapiUtilsCreateTemplateRequest) Set(val *GithubComTcrisseappPdfgenInternalHandlersRestapiUtilsCreateTemplateRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableGithubComTcrisseappPdfgenInternalHandlersRestapiUtilsCreateTemplateRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableGithubComTcrisseappPdfgenInternalHandlersRestapiUtilsCreateTemplateRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGithubComTcrisseappPdfgenInternalHandlersRestapiUtilsCreateTemplateRequest(val *GithubComTcrisseappPdfgenInternalHandlersRestapiUtilsCreateTemplateRequest) *NullableGithubComTcrisseappPdfgenInternalHandlersRestapiUtilsCreateTemplateRequest {
	return &NullableGithubComTcrisseappPdfgenInternalHandlersRestapiUtilsCreateTemplateRequest{value: val, isSet: true}
}

func (v NullableGithubComTcrisseappPdfgenInternalHandlersRestapiUtilsCreateTemplateRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGithubComTcrisseappPdfgenInternalHandlersRestapiUtilsCreateTemplateRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


