/*
PDFGen API

The PDFGen API for HTML to PDF generation.

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the TemplateResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TemplateResponse{}

// TemplateResponse struct for TemplateResponse
type TemplateResponse struct {
	Alias *string `json:"alias,omitempty"`
	CreatedAt *string `json:"created_at,omitempty"`
	Html *string `json:"html,omitempty"`
	Id *string `json:"id,omitempty"`
	LastGenerated *string `json:"last_generated,omitempty"`
	Name *string `json:"name,omitempty"`
}

// NewTemplateResponse instantiates a new TemplateResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTemplateResponse() *TemplateResponse {
	this := TemplateResponse{}
	return &this
}

// NewTemplateResponseWithDefaults instantiates a new TemplateResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTemplateResponseWithDefaults() *TemplateResponse {
	this := TemplateResponse{}
	return &this
}

// GetAlias returns the Alias field value if set, zero value otherwise.
func (o *TemplateResponse) GetAlias() string {
	if o == nil || IsNil(o.Alias) {
		var ret string
		return ret
	}
	return *o.Alias
}

// GetAliasOk returns a tuple with the Alias field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TemplateResponse) GetAliasOk() (*string, bool) {
	if o == nil || IsNil(o.Alias) {
		return nil, false
	}
	return o.Alias, true
}

// HasAlias returns a boolean if a field has been set.
func (o *TemplateResponse) HasAlias() bool {
	if o != nil && !IsNil(o.Alias) {
		return true
	}

	return false
}

// SetAlias gets a reference to the given string and assigns it to the Alias field.
func (o *TemplateResponse) SetAlias(v string) {
	o.Alias = &v
}

// GetCreatedAt returns the CreatedAt field value if set, zero value otherwise.
func (o *TemplateResponse) GetCreatedAt() string {
	if o == nil || IsNil(o.CreatedAt) {
		var ret string
		return ret
	}
	return *o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TemplateResponse) GetCreatedAtOk() (*string, bool) {
	if o == nil || IsNil(o.CreatedAt) {
		return nil, false
	}
	return o.CreatedAt, true
}

// HasCreatedAt returns a boolean if a field has been set.
func (o *TemplateResponse) HasCreatedAt() bool {
	if o != nil && !IsNil(o.CreatedAt) {
		return true
	}

	return false
}

// SetCreatedAt gets a reference to the given string and assigns it to the CreatedAt field.
func (o *TemplateResponse) SetCreatedAt(v string) {
	o.CreatedAt = &v
}

// GetHtml returns the Html field value if set, zero value otherwise.
func (o *TemplateResponse) GetHtml() string {
	if o == nil || IsNil(o.Html) {
		var ret string
		return ret
	}
	return *o.Html
}

// GetHtmlOk returns a tuple with the Html field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TemplateResponse) GetHtmlOk() (*string, bool) {
	if o == nil || IsNil(o.Html) {
		return nil, false
	}
	return o.Html, true
}

// HasHtml returns a boolean if a field has been set.
func (o *TemplateResponse) HasHtml() bool {
	if o != nil && !IsNil(o.Html) {
		return true
	}

	return false
}

// SetHtml gets a reference to the given string and assigns it to the Html field.
func (o *TemplateResponse) SetHtml(v string) {
	o.Html = &v
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *TemplateResponse) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TemplateResponse) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *TemplateResponse) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *TemplateResponse) SetId(v string) {
	o.Id = &v
}

// GetLastGenerated returns the LastGenerated field value if set, zero value otherwise.
func (o *TemplateResponse) GetLastGenerated() string {
	if o == nil || IsNil(o.LastGenerated) {
		var ret string
		return ret
	}
	return *o.LastGenerated
}

// GetLastGeneratedOk returns a tuple with the LastGenerated field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TemplateResponse) GetLastGeneratedOk() (*string, bool) {
	if o == nil || IsNil(o.LastGenerated) {
		return nil, false
	}
	return o.LastGenerated, true
}

// HasLastGenerated returns a boolean if a field has been set.
func (o *TemplateResponse) HasLastGenerated() bool {
	if o != nil && !IsNil(o.LastGenerated) {
		return true
	}

	return false
}

// SetLastGenerated gets a reference to the given string and assigns it to the LastGenerated field.
func (o *TemplateResponse) SetLastGenerated(v string) {
	o.LastGenerated = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *TemplateResponse) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TemplateResponse) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *TemplateResponse) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *TemplateResponse) SetName(v string) {
	o.Name = &v
}

func (o TemplateResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TemplateResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Alias) {
		toSerialize["alias"] = o.Alias
	}
	if !IsNil(o.CreatedAt) {
		toSerialize["created_at"] = o.CreatedAt
	}
	if !IsNil(o.Html) {
		toSerialize["html"] = o.Html
	}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.LastGenerated) {
		toSerialize["last_generated"] = o.LastGenerated
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	return toSerialize, nil
}

type NullableTemplateResponse struct {
	value *TemplateResponse
	isSet bool
}

func (v NullableTemplateResponse) Get() *TemplateResponse {
	return v.value
}

func (v *NullableTemplateResponse) Set(val *TemplateResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableTemplateResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableTemplateResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTemplateResponse(val *TemplateResponse) *NullableTemplateResponse {
	return &NullableTemplateResponse{value: val, isSet: true}
}

func (v NullableTemplateResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTemplateResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


